name: generate-pcb-artifacts

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.kibot.yaml'
    - '.github/workflows/generate-pcb-artifacts.yaml'
  pull_request:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.kibot.yaml'
    - '.github/workflows/generate-pcb-artifacts.yaml'

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Run ERC
      run: kibot -d output -s run_erc -i

    - name: Run DRC
      run: kibot -d output -s run_erc -i

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output
