name: generate-pcb-artifacts

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.kibot.yaml'
    - '.github/workflows/generate-pcb-artifacts.yaml'
  pull_request:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
    - '**.kibot.yaml'
    - '.github/workflows/generate-pcb-artifacts.yaml'

jobs:
  ERC:
    runs-on: ubuntu-latest
    container: setsoft/kicad_auto:latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Output
      uses: INTI-CMNB/KiBot@v0.7.0
      with:
      # Required - kibot config file
        config: config.kibot.yaml
      # optional - prefix to output defined in config
        dir: output
      # optional - schematic file
        schema: '*.sch'
      # optional - PCB design file
        board: '*.kicad_pcb'

    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output

